#!/usr/bin/env groovy

/*
This script runs the migration from V1 to V2 Production
*/

pipeline {

    agent {
        dockerfile {
            filename 'notifications/Dockerfile'
            args '-e NOTIFICATIONS_APP_USER_EMAIL=$NOTIFICATIONS_APP_USER_EMAIL -e NOTIFICATIONS_APP_USER_PASSWORD=$NOTIFICATIONS_APP_USER_PASSWORD'

        }
    }

    stages {
        stage('Call notifications endpoint') {
            steps {
                echo 'Calling notifications endpoint...'
                sh 'chmod -R +x *'
                sh './notifications/runner.sh'
            }
        }
    }
    post {
        failure {
            script {
                def payload = """{
                    "content": "🚨 Build Failed: ${env.JOB_NAME} #${env.BUILD_NUMBER}"
                }"""

                sh """
                curl -X POST -H "Content-Type: application/json" -d '${payload}' ${env.WEBHOOK_URL}
                """
            }
        }
    }
}
